---
AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Stack Set

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-08333bccc35d71140  # Specify the desired AMI ID
      KeyName: ohio_key
      SecurityGroupIds:
        - sg-05b09f26ac04da63d  # Specify the desired security group ID
      SubnetId: subnet-05e9bb71c97ad3275  # Specify the desired subnet ID
      Tags:
        - Key: Name
          Value: MyInstance1

Outputs:
  EC2Instance:
    Description: EC2 instance created by the stack
    Value: !Ref EC2Instance
